CREATE TABLE TODO (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255),
    description VARCHAR(255),
    completed BOOLEAN,
    deadline DATE
);

CREATE TABLE LABEL (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL
);

CREATE TABLE TODO_LABEL (
    todo_id BIGINT NOT NULL,
    label_id BIGINT NOT NULL,
    PRIMARY KEY (todo_id, label_id),
    FOREIGN KEY (todo_id) REFERENCES TODO(id) ON DELETE CASCADE,
    FOREIGN KEY (label_id) REFERENCES LABEL(id) ON DELETE CASCADE
);

CREATE TABLE "USER" (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

